### ISSUE TITLE
Error import mset

### ISSUE THREAD

**Issue by mactone** [maminian/caterpillar_mset#1]
I installed the mset by using
` pip install mset`

When I tried to import mset, error shown as below
```
 File "/usr/local/lib/python3.6/dist-packages/mset/__init__.py", line 765
    class CameraObject.CameraLens:
                      ^
SyntaxError: invalid syntax
```

What happened?

**Comment by mactone** [comment]
I am stuipid to use pip install mset which installed another package. 
Now, the problem is solved.

**Comment by maminian** [comment]
Thanks for your interest! Yeah, that's right, this isn't registered on pip; you'd simply clone it and import the modules once you've added the folder to your python path.
