### ISSUE TITLE
Academic attribution question

### ISSUE THREAD

**Issue by fshriver** [maminian/caterpillar_mset#3]
Hi,

Interesting library! Do you have more detailed sources for the two nonlinear operators you include, otimes1_ij and otimes2_ij? I'm afraid the "Wang paper" one is a bit too vague for me to track down, and specifically googling "Dreissigmeier" in quotes returns nothing.

Thanks in advance!

**Comment by maminian** [comment]
Good question -- the comments in the code themselves are vague; I should add something to the readme.

To answer your question, these are the "Dreissigmeier" and "Wang" papers the code is referring to:

* Thompson J, Dreisigmeyer DW, Jones T, Kirby M, Ladd J. 2010. Accurate fault prediction of BlueGene/P RAS logs via geometric reduction, pp. 8–14. See https://dl.acm.org/citation.cfm?id=1909521
* Wang K, Thompson J, Peterson C, Kirby M. 2015. Identity maps and their extensions on parameter spaces: applications to anomaly detection in video. In Proc. 2015 Science and Information Conf. (SAI), London, UK, 28–30 July 2015, pp. 345–351. New York, NY: IEEE.

The paper I used this particular code with is here (send me an email if you can't get access to the pdf; happy to share): https://royalsocietypublishing.org/doi/full/10.1098/rsfs.2019.0086

**Comment by maminian** [comment]
Please check the readme in the "Citation" section for the (fully correct) citations now. Let me know if you have any other questions!

**Comment by fshriver** [comment]
I lost track of this - thanks so much for the references and updating the readme! The directions to the two papers + yours are very much appreciated!

Merry Christmas!
